#!/usr/bin/with-contenv bash

if [ $JACKETT_PRE_BUILD -eq 1 ]; then
  url="https://api.github.com/repos/Jackett/Jackett/releases"
  vers="PRE-RELEASE"
else
  url="https://api.github.com/repos/Jackett/Jackett/releases/latest"
  vers="RELEASE"
fi

echo "**** install jackett $vers ****"
mkdir -p /app/Jackett
jack_tag=$(curl -sX GET "$url" | awk '/tag_name/{print $4;exit}' FS='[""]')
curl -o /tmp/jacket.tar.gz -L https://github.com/Jackett/Jackett/releases/download/$jack_tag/Jackett.Binaries.Mono.tar.gz
tar xf /tmp/jacket.tar.gz -C /app/Jackett --strip-components=1

if [ $JACKETT_TRACKERFIX -eq 1 ]; then
  echo "***** TEMP FIX FOR TRACKERS *****"
  if [[ -n "$(ls -A /trackersfix 2>/dev/null)" ]]
  then
    echo "#### copy yml files from /trackersfix/ ####"
    cp /trackersfix/* /app/Jackett/Definitions/
  fi
  
  if [[ -n "$(ls -A /config/trackersfix 2>/dev/null)" ]]
  then
    echo "#### copy yml files from /config/trackersfix/ ####"
    cp /config/trackersfix/* /app/Jackett/Definitions/
  fi
fi

echo "**** fix for host id mapping error ****"
chown -R root:root /app/Jackett

chown -R abc:abc \
	/app \
	/config \
	/downloads
